In [125]:
import numpy as np

A = np.array([1,2,3,4], dtype=int)
A.shape
print(A)


[1 2 3 4]


In [126]:
print(np.zeros((2, 3), dtype=float))

[[0. 0. 0.]
 [0. 0. 0.]]


In [127]:
print(np.ones((2, 3), dtype=float))

[[1. 1. 1.]
 [1. 1. 1.]]


In [128]:
print(np.full((3,3),7, dtype=int))

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [129]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [130]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [131]:
np.random.rand(2,3)

array([[0.81546767, 0.15299858, 0.64994697],
       [0.43756393, 0.63928449, 0.19552645]])

In [132]:
np.random.randint(0,5,(2,3))

array([[1, 2, 0],
       [3, 4, 3]], dtype=int32)

# Part 2

In [133]:
A.shape

(4,)

In [134]:
A.ndim
A.dtype

dtype('int64')

In [135]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[::2,2:])


[[ 3  4]
 [11 12]]


In [136]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20]])
print(a[1::2,::-1])

[[ 8  7  6  5]
 [16 15 14 13]]


In [137]:
print(a[1:3,-2:])

[[ 7  8]
 [11 12]]


In [138]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(c))
print(np.sum(c, axis=0))
print(np.sum(c, axis=1))

45
[12 15 18]
[ 6 15 24]


In [139]:
print(np.min(c))
print(np.max(c))
print(np.mean(c))
print(np.median(c))
print(np.std(c))
print(np.var(c))
print(np.cumsum(c))
print(np.cumprod(c))

1
9
5.0
5.0
2.581988897471611
6.666666666666667
[ 1  3  6 10 15 21 28 36 45]
[     1      2      6     24    120    720   5040  40320 362880]


In [140]:
l = np.arange(1,7)
print(l)
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye(3))
print(np.random.rand(5))

[1 2 3 4 5 6]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.08067723 0.59737259 0.90826609 0.96490402 0.18815894]


In [141]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)


2
(2, 3)
6
int64


In [142]:
A = np.array([[10,20,30],[40,50,60],[70,80,90]])
[[30],[60],[90]]
print(A[1,1])
print(A[0])
print(A[:,2])
print(A[:,-1])
print(A[:2,1:])


50
[10 20 30]
[30 60 90]
[30 60 90]
[[20 30]
 [50 60]]


# -6-Reshape et modification de la structure

In [143]:
A = np.array([[1, 2, 4, 5]])
A.reshape(2,2)


array([[1, 2],
       [4, 5]])

In [144]:
np.resize(A,(4,4))

array([[1, 2, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 4, 5]])

In [145]:
B = A.flatten()
print(B)
B[0] = 100
print(B)
print(A)
C= A.ravel()
print(C)
C[0] = 100
print(C)
print(A)

[1 2 4 5]
[100   2   4   5]
[[1 2 4 5]]
[1 2 4 5]
[100   2   4   5]
[[100   2   4   5]]


In [146]:
A = np.array([1, 2, 3])

B = A[:, np.newaxis]

print(B)
c=A[np.newaxis,:]
print(c)

[[1]
 [2]
 [3]]
[[1 2 3]]


In [147]:
A = np.array([1, 2, 3])

B = np.expand_dims(A, axis=1)
print(B)

[[1]
 [2]
 [3]]


In [148]:
A = np.array([[[1, 2, 3]]])
np.squeeze(A)

array([1, 2, 3])

In [149]:
A = np.array([1, 2, 3])
B = np.append(A, 4)

print(B)
B = np.insert(B, 1, 99)
print(B)
B = np.delete(B, 1)
print(B)

[1 2 3 4]
[ 1 99  2  3  4]
[1 2 3 4]


# -7-Filtrage et indexation avancée et Tri


In [150]:
B = np.array([[5, 15, 25],
[35, 45, 55],
[65, 75, 85]])

lines = np.array([True, False, True])
print(B[lines, :])

col = np.array([False, True, False])
print(B[:, col])

elements = np.array([[True, False, False],
[False, False, False],
[False, False, True]])
print(B[elements])

[[ 5 15 25]
 [65 75 85]]
[[15]
 [45]
 [75]]
[ 5 85]


In [151]:
A = np.array([[5, 10, 25],
[35, 45, 55],
[65, 75, 80]])
print(np.where(A % 2 == 0))
print(np.where(A % 2 == 0, A, 0))

(array([0, 2]), array([1, 2]))
[[ 0 10  0]
 [ 0  0  0]
 [ 0  0 80]]


In [152]:
print(np.where(A % 2 == 0))

(array([0, 2]), array([1, 2]))


In [153]:
A = np.array([[5, 10, 25],
[35, 45, 55],
[65, 75, 80]])
print(np.argmax(A))
# Flattened array: [5, 10, 25, 35, 45, 55, 65, 75, 80]
print(np.argmin(A, axis=None))

8
0


In [154]:
A = np.array([
 [2, 3, 25],
 [35, 45, 2],
 [4, 3, 4]
])

u, index, inverse, counts = np.unique(
    A,
    return_index=True,
    return_inverse=True,
    return_counts=True
)

print("u:", u)
print("index:", index)
print("inverse:", inverse)
print("counts:", counts)
A = np.array([
 [2, 3, 25],
 [35, 45, 2],
 [4, 3, 4]
])

u: [ 2  3  4 25 35 45]
index: [0 1 6 2 3 4]
inverse: [[0 1 3]
 [4 5 0]
 [2 1 2]]
counts: [2 2 2 1 1 1]


In [155]:
A = np.array([[9, 1, 7],
              [3, 5, 2]])

print(np.sort(A, axis=None))

[1 2 3 5 7 9]


In [156]:
A = np.array([[9, 1, 7],
              [3, 5, 2]])

print(np.sort(A, axis=1))

[[1 7 9]
 [2 3 5]]


In [157]:
A = np.array([[9, 1, 7],
              [3, 5, 2]])

print(np.sort(A, axis=0))

[[3 1 2]
 [9 5 7]]


In [158]:
A = np.array([[9, 1, 7],
              [3, 5, 2]])

print(np.sort(A, axis=-1))

[[1 7 9]
 [2 3 5]]


In [159]:
A = np.array([50, 10, 30])
print(np.argsort(A))

[1 2 0]


In [160]:
A = np.array([1,2,3,1,2])
print(np.argsort(A, kind='mergesort'))
print(np.argsort(A, kind='stable'))
print(np.argsort(A, kind='quicksort'))
print(np.argsort(A, kind='heapsort'))


[0 3 1 4 2]
[0 3 1 4 2]
[0 3 1 4 2]
[0 3 1 4 2]


In [161]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

print(np.where(a > 2))
indices = np.where(a > 2)
print(a[np.where(a > 2)])


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
(array([1, 1, 2, 2]), array([0, 1, 0, 1]))
[3 4 5 6]


In [162]:
a = np.array([[1,2], 
              [3, 4],
              [5, 6]])
print(np.any(a > 3, axis=0))
print(np.any(a > 3, axis=1))

[ True  True]
[False  True  True]


In [163]:
print(np.all(a > 3, axis=0))
print(np.logical_and(a > 2, a < 5))

[False False]
[[False False]
 [ True  True]
 [False False]]


In [164]:
print(np.logical_or(a < 2, a > 5 ))

[[ True False]
 [False False]
 [False  True]]


In [165]:
print(np.logical_not(a > 3))
print(a[np.logical_not(a > 3)])

[[ True  True]
 [ True False]
 [False False]]
[1 2 3]


In [166]:
b=a.copy()
print(b)
b[0,0] = 100
print(b)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[100   2]
 [  3   4]
 [  5   6]]
[[1 2]
 [3 4]
 [5 6]]


In [167]:
print(np.concatenate([a, b], axis=0 ))

[[  1   2]
 [  3   4]
 [  5   6]
 [100   2]
 [  3   4]
 [  5   6]]


In [168]:
print(np.concatenate([a, b], axis=1))

[[  1   2 100   2]
 [  3   4   3   4]
 [  5   6   5   6]]


In [169]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(np.split(a,3))
print(np.sum(a,axis=0))#axis 0 is for rows but it sums the columns

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[ 9 12]


In [170]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(np.stack((A,B), axis=0))
print(np.stack((A,B), axis=1))
print(np.hstack((A,B)))
print(np.vstack((A,B)))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [171]:
print(np.random.rand(3, 2))

[[0.65761251 0.43565903]
 [0.20187893 0.13146995]
 [0.98600203 0.82262094]]


In [172]:
np.random.randn(3, 2)#values around 0 possibly negative

array([[-1.2369758 ,  0.96370737],
       [ 0.19876917,  0.29436471],
       [-0.23107919, -1.14100777]])

In [173]:
print(np.random.randint(1, 5, (3,3)))

[[3 4 1]
 [3 1 3]
 [3 3 1]]


In [174]:
a = np.array([[1,2],
             [3, 4],
            [5, 6]])

np.random.shuffle(a)
print(a)
np.random.shuffle(a)
print(a)

[[1 2]
 [5 6]
 [3 4]]
[[3 4]
 [5 6]
 [1 2]]


In [175]:
b=np.array([1, 2, 3, 4, 5])
np.random.choice(b,size=3)#b must be 1D array or 1D list

array([4, 3, 3])

# tp rev

In [176]:
A= np.array([[1,2,3],
     [4,5,6]])

print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(2, 3)
6
int64


In [177]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = a[0:2, 1:3]
print(b)


[[2 3]
 [5 6]]


In [178]:
b[0,0] = 99
print(b)
print(a)

[[99  3]
 [ 5  6]]
[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]


In [179]:
A = np.array([1,2,3,4,5,6])
A.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
b=A.flatten()
print(b)

[1 2 3 4 5 6]


In [181]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])
print(A @ B)
print(np.matmul(A, B))
print(np.dot(A, B))
print(A.T)
print(A.transpose())
print(np.linalg.det(A))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
-2.0000000000000004


# filtering


In [182]:
A = np.array([[1,2,3],
              [4,5,6]])
B = A[A>3]
print(B)

[4 5 6]


# get indexis

In [183]:
print(np.where(A>3))
print(np.argwhere(A>3))

(array([1, 1, 1]), array([0, 1, 2]))
[[1 0]
 [1 1]
 [1 2]]


In [184]:
A= np.where(A>3, 0, A)
print(A)
A = np.array([[1,2,3],
              [4,5,6]])
A[A > 3] = 0
print(A)

[[1 2 3]
 [0 0 0]]
[[1 2 3]
 [0 0 0]]


In [186]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.vstack((A,B)))
print(np.hstack((A,B)))
print(np.stack((A,B), axis=0))
print(np.stack((A,B), axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
